### ISSUE TITLE
Collect symphony user profiles for various users

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/mylibrary#118]
⬇️

**Comment by saseestone** [comment]
## Fee borrower
```
Fee borrowers are distinguishable by User Profile:
MXFEE
MXFEE-BUS
MXFEE-LAW
MXFEE-NO25
```

## Sponsor
```
Sponsors are distinguishable because of User Group properties:
Group responsibility = SPONSOR
```

## Proxy borrower
Proxies are distinguishable because of User Group properties:
Group responsibility = PROXY
```

## Research group
```
Research groups are distinguishable because they have a User Group associated with their account. Note: Group name in the sym policy is encoded (It's a combo of the Faculty member's department code and how many research groups they have...and encoded because of some long-term privacy concerns in the logs.)  For My Account we'll want to use the Faculty member's name as the "Group Name".  The Faculty member's name is also used in the name field for these accounts. User account name is "Faculty sponsor last name, First name (P=lastnameofproxy)"  Example is: Seestone, Sarah (P=Proxy last name)
```

## SUNet users(?)
```
We do have the SUNet ID in the sym user record.  I believe it's labelled "Group Name".  (Left over field swapping from when Sirsi didn't have a user field for auth... and we never changed it....) @shelleydoljack can confirm.
```
