### ISSUE TITLE
Fines details [story]

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#130]
Ensure the payable fines display the following information:

Above the "fold":
- [x] Reason
- [x] $amount
- [x] Title
- [x] Author

Expand to:
- [x] Billed on: (date)
- [x] Borrowed on: (date)
- [x] Days overdue: count
- [x] Assumed lost on: (date) (if assumed lost)
- [x] (specific type) fee: ($amount) (substitute the `Fine#nice_status` value for specific type.. adding `fee` as needed?)
- [x] Source: (SUL library brief name)

E.g:

<img width="378" alt="Screen Shot 2019-07-17 at 13 51 07" src="https://user-images.githubusercontent.com/111218/61410842-f5465280-a899-11e9-9f3d-64faf2c95572.png">

**Comment by jkeck** [comment]
A few questions about the two remaining pieces for this ticket.

1. `Borrowed on: (date)`
  * Does anybody know how to get this data?  It wasn't immediately obvious how to get, from the `blockList` response to when the particular item that the patron was being charged for checkout date (for this transaction)
2. `Assumed lost on: (date)`
  * What constitutes something that is assumed lost?  I have the current location of the item, however; if the item is replaced, will the current location associated still be accurate?  We could whitelist the status keys that resolve to a `Lost item` label if that would be a more robust solution.
  * Is the date that the item is assumed lost the date that block was created?  Should we get that information from somewhere more explicit than implying from the block creation date?

**Comment by jvine** [comment]
1. From what I learned from Sarah yesterday about this process, I think it's likely not possible to get both the Borrowed and Days overdue amounts for Assumed lost items. The lost item fee is a separate record from the original checkout. I think these two values may be available only for Overdue fees. 

2. Looking at the Labels & content doc - the "Assumed lost on (date)" has been removed because it is the same as the "Billed" date. 

Assumed lost goes like this:
Item is very overdue on the checkouts tab. It passes a threshold. Someone says "bill this one", and _separate_ bill records are created for the lost item fee and processing fee. (The lost item fee is high and will block the user.) The overdue item on the checkouts tab remains there, now marked Assumed lost. The user is still responsible for the overdue fine - the lost item fee does not replace it. But they can't pay the overdue until they either:
a) return the item (at which point the lost item fee is cleared; but the user still has to pay the processing fee - and now the overdue fee)
b) pay the lost item fee, which essentially returns the book. Then same, they have to pay the overdue fee.

Lesson: don't lose books, kids.
