### ISSUE TITLE
Define what library-specific links we should show for each tab

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#141]
Each tab in My Account will have a "information" section at the bottom, which will primarily host links to website content related to the content of that tab. 

### Login page

`<h2>Policies & information</h2>`
- Access & privileges (https://library.stanford.edu/using/access-and-privileges)
- Fee-based library memberships (https://library.stanford.edu/using/access-and-privileges/privileges-university-library-affiliates/fee-based-library-memberships)

### Summary

`<h2>Policies & information</h2>`
- Circulation policies (https://library.stanford.edu/using/borrow-renew-return)
- Borrower responsibilities (https://library.stanford.edu/using/access-and-privileges/borrower-responsibilities)
- Suspended privileges (https://library.stanford.edu/using/access-and-privileges/suspended-privileges)

### Checkouts

`<h2>Policies & information</h2>`
- Renewal policies (https://library.stanford.edu/using/borrow-renew-return/renew)
- Did you lose an item? (https://library.stanford.edu/using/borrow-renew-return/did-you-lose-item)
- Returning items by mail (https://library.stanford.edu/using/borrow-renew-return/return)

### Requests

`<h2>If your request isn't listed</h2>`
- Hoping the first paragraph will not be required because we will list mediated requests...
- Text correction to the current link:
    - Check Interlibrary Borrowing (https://sulils.stanford.edu) for requests made through Stanford Libraries Interlibrary Services
_(note title case of Interlibrary Borrowing)_

### Fines
Remove the current "Refund policy" header and content, replace with:

`<h2>Policies & information</h2>`
- Fines and fees (https://library.stanford.edu/using/borrow-renew-return/fines-and-fees)
- Pay or contest a fine (https://library.stanford.edu/using/borrow-renew-return/pay-or-contest-fine)

**Comment by saseestone** [comment]
@jvine and I discussed this today and agreed that it will be better if we leave the footer generic, and instead determine context specific links out to appropriate library webpages to appear at the bottom of each tab - similar to JV's design for the Summary tab in her mockups.  I'll work on a list of suggested  links for each tab soon.

**Comment by jvine** [comment]
The global SUL footer is meant to be global. It has varied over time. It still has issues, but I am reluctant to change it yet again for an individual app. 

Each tab in My Account will have a "information" section at the bottom, which will primarily host links to website content related to the content of that tab. 

### Login page

`<h2>Policies & information</h2>`
- Access & privileges (https://library.stanford.edu/using/access-and-privileges)
- Fee-based library memberships (https://library.stanford.edu/using/access-and-privileges/privileges-university-library-affiliates/fee-based-library-memberships)

### Summary

`<h2>Policies & information</h2>`
- Circulation policies (https://library.stanford.edu/using/borrow-renew-return)
- Borrower responsibilities (https://library.stanford.edu/using/access-and-privileges/borrower-responsibilities)
- Suspended privileges (https://library.stanford.edu/using/access-and-privileges/suspended-privileges)

### Checkouts

`<h2>Policies & information</h2>`
- Renewal policies (https://library.stanford.edu/using/borrow-renew-return/renew)
- Did you lose an item? (https://library.stanford.edu/using/borrow-renew-return/did-you-lose-item)
- Returning items by mail (https://library.stanford.edu/using/borrow-renew-return/return)

### Requests

`<h2>If your request isn't listed</h2>`
- Hoping the first paragraph will not be required because we will list mediated requests...
- Text correction to the current link:
    - Check Interlibrary Borrowing (https://sulils.stanford.edu) for requests made through Stanford Libraries Interlibrary Services
_(note title case of Interlibrary Borrowing)_

### Fines
Remove the current "Refund policy" header and content, replace with:

`<h2>Policies & information</h2>`
- Fines and fees (https://library.stanford.edu/using/borrow-renew-return/fines-and-fees)
- Pay or contest a fine (https://library.stanford.edu/using/borrow-renew-return/pay-or-contest-fine)

### Formatting
Currently, the link icon is separated from the text by a space, which seems kind of fragile. Better maybe to do something like `a .sul-icons {margin-right: .5em;} globally? (Would also coincidentally fix the "View in Searchworks" links.)
