### ISSUE TITLE
Update "Reset PIN" email text

### ISSUE THREAD

**Issue by jvine** [sul-dlss/mylibrary#162]
**Questions**
- what is the from address? Can it be `<sul-privileges@stanford.edu>` so they can click Reply to ask a question?
- is it possible to include a logo image? 

**Text**
```
From:  Stanford Libraries 

Subject:  Stanford Libraries PIN Change Request

Body:
<logo>
<p>This email was sent in response to a request from My Library Account to change the PIN for account <b><loginID></b>.

<p style="font-size: 18pt;"><a href="<LINK>">Change my PIN</a></p>

<p>If you did not ask to change your PIN, ignore this email. This link will expire in XX hours.</p>

<p>Questions? Contact the Privileges desk at sul-privileges@stanford.edu or (650) 723-1492.</p>
```

**Outcome**

<img width="725" alt="PIN change request" src="https://user-images.githubusercontent.com/6945691/61422535-f9399b00-a8c0-11e9-93eb-32b71d0b37d2.png">

**Comment by shelleydoljack** [comment]
We cannot change the from address. This has been a thing since migrating to Linux and a constraint from Operations. All of our reports that Symphony sends out (like bill notices, overdue notices, orders, etc.) all should have different from email addresses but all we can do is set a specific reply-to address. The from address on production is "Stanford University Libraries" `sirsi at ${hostname} dot stanford dot edu`. Sometimes users end up sending a reply to this address and it gets bounced to our internal dev list email and the we (libsys) forwards it to the appropriate person.

I looked up in the online helps for web services and it doesn't mention anything about being able to embed a logo image. I will submit a SirsiDynix Support ticket about that but I think the answer is no. I'm also not sure if we have access to the login ID (this is the barcode, yes?) in the email template and I don't know when the token expires; more questions for SD Support.

**Comment by shelleydoljack** [comment]
Responses from SirsiDynix:
>There isn't a way I have found to add the barcode in the email. I tested it with a few different variables and wasn't able to get it to display in the email. There isn't a way to embed an image, but you could probably create an html img tag that points to an image on one of your servers. The token is valid for 20 minutes, unfortunately, there isn't a way to customize this timer.
>We were able to find that the Unicorn/Bin/mailpin.pl script is used for the email template, you could possibly customize it and put it into Bincustom.

**Comment by jvine** [comment]
Logo is optional, fine to leave it out.

Does barcode = Library ID? Unfortunate if we can't show it. Can we spin off a backlog ticket so we can revisit this if it becomes possible? Meanwhile, I guess change `change the PIN for account <b><loginID>` to `change the PIN for your account`.

**Comment by shelleydoljack** [comment]
I'm working on trying to get the library ID (user barcode) into the email. The mailpin.pl script can easily include it. Adding the logo might be trickier so a backlog ticket is an excellent idea.

**Comment by shelleydoljack** [comment]
Template email updated to include library ID and link expiration on dev and prod.
