### ISSUE TITLE
Requests tab doesn't work if the patron has no requests

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#178]
## Backtrace

    line 97 of [PROJECT_ROOT]/app/models/patron.rb: requests
    line 12 of [PROJECT_ROOT]/app/controllers/requests_controller.rb: index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/62116/faults/52390045)

**Comment by tallenaz** [comment]
Symphony gives me a different response, depending on whether I'm requesting from `mylibrary-dev` or `uat`.

dev:
```
... "blockList"=>[], "holdRecordList"=>[], "groupSettings"=>nil ...
```

uat:
```
... "blockList"=>[], "groupSettings"=>nil ...
```

Do we want the `Patron#requests` method to handle both kinds of response -- when there is no `holdRecordList`, and when there is and it points to `[]`? Or do we not expect Symphony to behave this way?

**Comment by shelleydoljack** [comment]
The response from Symphony between hitting the -dev and -prod web services servers should be the same as we are running the same versions of web services and Symphony on both. In web services administration, there is a resource security configuration that allows you to set fields to be either hidden, read-only, and some editable. For the resource holdRecord, there was one difference between -dev and -prod and a few differences for the other resources. I changed them so mostly everything is read-only and definitely no difference between the two servers. After resetting the web services connection to the ILS, I tested a call to get holdRecordList and now it returns an empty array. Unfortunately, I didn't test a call after each change in resource security configuration I made so now I'm not sure which particular field caused the problem, but it wasn't that a field in the holdRecord was hidden on -prod and not on -dev; it must have been a combination of holdRecord resource security configuration and user/patron security configuration. Interestingly, the field holdRecordList in user/patron security configuration on -prod is at the bottom while on -dev it is listed alphabetically. Very strange!

On top of making sure resource security configuration is the same in both web services, another thing to check when troubleshooting issues like these is to look at the command lists for the SYMWS user and make sure they are the same (which they are, I double-checked). Any changes made to that command list will require a Symphony restart (occurs daily) since it is a policy.

**Comment by tallenaz** [comment]
After the changes @shelleydoljack made to `symws` and deploying the latest `master` to `uat`, the requests tab works.

**Comment by shelleydoljack** [comment]
I just checked this in -uat and I get a "we're sorry something went wrong" page so I looked up my patron info to get my holdRecordList on -prod and it is not returning an empty holdRecordList array. I am going to open a ticket with SirsiDynix Support.

**Comment by shelleydoljack** [comment]
It looks like the root of the problem was due to the web services restart happening while Symphony was down (even though this didn't seem to be an issue for -dev it was for -prod). The restart was fixed yesterday in puppet and this morning's restart occurred at the right time. Now a `holdRecordList=[]` is returned for patrons without any holds and without manually having to reset the web services connections to Symphony.
