### ISSUE TITLE
Queue position depends on title-level or copy-level holds

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/mylibrary#243]
The Symphony web services API returns the fields `queuePosition` and `queueLength` for a given holdRecord. The values of these fields return different things if the hold is title-level or copy-level. For instance, a user has a copy-level hold on an item for ckey 9499733. I submitted a request for this item by clicking on the request link at `https://searchworks-morison.stanford.edu/view/9499733`. I now have a title-level hold on the item (see holdType = TITLE):
```
{
  "resource": "/circulation/holdRecord",
  "key": "1675147",
  "fields": {
    "bib": {
      "resource": "/catalog/bib",
      "key": "9499733"
    },
    "item": {
      "resource": "/catalog/item",
      "key": "9499733:5:1"
    },
    "patron": {
      "resource": "/user/patron",
      "key": "221417"
    },
    "beingHeldDate": null,
    "comment": "",
    "expirationDate": null,
    "fillByDate": "2020-07-24",
    "holdPriority": null,
    "holdRange": {
      "resource": "/policy/holdRange",
      "key": "SYSTEM"
    },
    "holdType": "TITLE",
    "inactiveReason": null,
    "pickupLibrary": {
      "resource": "/policy/library",
      "key": "GREEN"
    },
    "placedDate": "2019-07-24",
    "placedLibrary": {
      "resource": "/policy/library",
      "key": "SUL"
    },
    "queueLength": 1,
    "queuePosition": 1,
    "recallStatus": "STANDARD",
    "selectedItem": {
      "resource": "/catalog/item",
      "key": "9499733:5:1"
    },
    "status": "PLACED",
    "suspendBeginDate": null,
    "suspendEndDate": null
  }
}
```
For me, I'm now 1 of 1 in the queue. I then submitted a request for this item through searchworks for the SUPER3 user. I'm now 1 of 2 in the queue and SUPER3 is 2 of 2. 

There are copy-level holds on this bib record for other users. When we look at the hold record list for them, there are 1 of 2 and 1 of 2, respectively (how are they both in first?):
```
{
  "resource": "/circulation/holdRecord",
  "key": "1675109",
  "fields": {
    "bib": {
      "resource": "/catalog/bib",
      "key": "9499733"
    },
    "item": {
      "resource": "/catalog/item",
      "key": "9499733:6:1"
    },
    "patron": {
      "resource": "/user/patron",
      "key": "186734"
    },
    "beingHeldDate": null,
    "comment": "",
    "expirationDate": null,
    "fillByDate": "2020-06-19",
    "holdPriority": null,
    "holdRange": {
      "resource": "/policy/holdRange",
      "key": "SYSTEM"
    },
    "holdType": "COPY",
    "inactiveReason": null,
    "pickupLibrary": {
      "resource": "/policy/library",
      "key": "GREEN"
    },
    "placedDate": "2019-06-20",
    "placedLibrary": {
      "resource": "/policy/library",
      "key": "GREEN"
    },
    "queueLength": 2,
    "queuePosition": 1,
    "recallStatus": "RUSH",
    "selectedItem": {
      "resource": "/catalog/item",
      "key": "9499733:6:1"
    },
    "status": "PLACED",
    "suspendBeginDate": null,
    "suspendEndDate": null
  }
}
```
The queueLength is 2 because another use has a copy-level hold on the record BUT the copy-level hold for these users are on different item keys! This person's place in the queue is 1 of 2:
```
{
  "resource": "/circulation/holdRecord",
  "key": "1665322",
  "fields": {
    "bib": {
      "resource": "/catalog/bib",
      "key": "9499733"
    },
    "item": {
      "resource": "/catalog/item",
      "key": "9499733:6:3"
    },
    "patron": {
      "resource": "/user/patron",
      "key": "507757"
    },
    "beingHeldDate": null,
    "comment": "",
    "expirationDate": null,
    "fillByDate": "2019-12-12",
    "holdPriority": null,
    "holdRange": {
      "resource": "/policy/holdRange",
      "key": "SYSTEM"
    },
    "holdType": "COPY",
    "inactiveReason": null,
    "pickupLibrary": {
      "resource": "/policy/library",
      "key": "GREEN"
    },
    "placedDate": "2018-12-12",
    "placedLibrary": {
      "resource": "/policy/library",
      "key": "SUL"
    },
    "queueLength": 2,
    "queuePosition": 1,
    "recallStatus": "RUSH",
    "selectedItem": {
      "resource": "/catalog/item",
      "key": "9499733:6:3"
    },
    "status": "PLACED",
    "suspendBeginDate": null,
    "suspendEndDate": null
  }
}
```
Summary: the hold placed for a checked out item through searchworks is a title-level hold. The queue for title-level holds are separate from the queue for copy-level holds. I guess an outstanding question is: when are copy-level holds created?

**Comment by saseestone** [comment]
As Shelley has said, when recalls/holds are placed using the Request App (and occasionally by staff in the WorkFlows app) they are created as TITLE level holds.  The level of the hold stays "TITLE" until a specific copy on the record is identified and "trapped" to fulfill the hold.  Once a specific copy has been "trapped", the hold level changes to COPY.  Then only that copy of the work can fulfill the hold.  I'm certain that's why both COPY holds in the example above show "1".

NOTE: If there are multiple copies of the work, the TITLE hold appears on each copy of the work until one copy is "trapped" to fulfill the hold.  Then the hold turns to a COPY, hold and the hold appears only on that copy. 

"Trapping" the hold happens in a few different ways.  
1. If there is an available copy of the work on the shelf, then the staff is alerted (via Symphony report) to pull the item.  Staff find the item and "trap" the hold in WorkFlows.  
2. If a copy of the work is INTRANSIT and the staff scan the barcode, WorkFlows "traps" the hold and alerts the staff to route the item to the hold pickup library. (This happens even if the staff have been alerted to pull another available copy from the shelf.  Basically which ever copy gets scanned first will be "trapped".
3. If there are no copies available on the shelf, then Symphony selects a copy of the work to recall from a user.  Once the recall is sent out, the hold level changes to COPY.

@shelleydoljack I looked in the WorkFlows helps to see if I could find any information on how they determine the hold queue, but I can't find anything helpful.

As discussed, I think we can have this hold queue display be a little "fuzzy" for launch of the app, and then we can see what comes back in user feedback.  What will be important is that a user in a long hold queue (e.g. more than 3) has an indication that there are many other users ahead of them.  I'm less concerned that we show their place exactly in hold queues of 1 or 2 on a complicated multi-copy record.
