### ISSUE TITLE
Add placeholder content if there are no checkouts / requests / fines

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#267]

**Comment by jvine** [comment]
If there are no checkouts/requests/fines, currently the user gets a blank page with just the links section. In order to explicitly indicate "nothing to see here",  retain the primary heading(s) for that page, and indicate 0 (as in the nav).

(Note that on the Checkouts and Requests page, the presence of the `<div class="d-flex justify-content-between">` around the `h2` is going to make the spacing between sections inconsistent.)

<img width="556" alt="checkouts 0" src="https://user-images.githubusercontent.com/6945691/61982889-05a1b000-afb3-11e9-8c2f-64a9800d2e99.png">
<img width="578" alt="requests 0" src="https://user-images.githubusercontent.com/6945691/61982891-05a1b000-afb3-11e9-8bb8-5ad96bc0be4b.png">
<img width="576" alt="fines 0" src="https://user-images.githubusercontent.com/6945691/61982888-05a1b000-afb3-11e9-9c81-d34f02952a60.png">
