### ISSUE TITLE
What is the app behavior when a patron is barred?

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#294]

**Comment by jvine** [comment]
Barred patrons can see everything.

They cannot renew checkouts.
- suppress the bulk Renew button on Summary and Checkouts
- will the item-level renewal button be suppressed automatically by the eligibility check? 

By policy, they are probably able to modify requests (because they can still request items). 

They cannot pay fines because we have nowhere to send the receipt.
- suppress the Pay now button on Summary and Fines

@saseestone ?

**Comment by jvine** [comment]
See #295 for details about button disabling/suppressing. Button text should be `Renewals barred`.

(Note that @saseestone has verbally approved the no-fine-payment change for barred users.)
