### ISSUE TITLE
What is the application behavior when Symphony is down?

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#298]
It seems like we can expect Symphony to be unavailable on a weekly basis (during normal SUL outage windows), sometimes for multiple hours.

**Comment by jvine** [comment]
My Account is up, Symphony is down, user can't actually do or see anything.

Instead of a flash message or something similar, I'd like to replace the "login" sections of the Home/Login page with a message, like so, killing 2 birds by suppressing the login buttons and placing the information where people will be looking for their login button:

<img width="690" alt="Screen Shot 2019-07-30 at 5 48 45 PM" src="https://user-images.githubusercontent.com/6945691/62175372-53d7eb80-b2f2-11e9-90f9-66491713781d.png">


```
    <h2>Temporarily unavailable</h2>
    <p>We're sorry, my Library Account is unavailable while its underlying systems are undergoing maintenance. </p><p>If you need help with your account, email <a href="mailto:greencirc@stanford.edu">greencirc@stanford.edu</a> or call (650) 723-1493.</p>
```

Simple mailto link, no popup.
