### ISSUE TITLE
Display reason for non-renewable items

### ISSUE THREAD

**Issue by jvine** [sul-dlss/mylibrary#349]
This detail fell out of the mockups at some point without my noticing.

When an item is not renewable online, the expanded content is meant to display a message indicating the reason. Initially, the reason text replaced the button, but I think it's better as part of the `<dt>` list.

<img width="391" alt="Screen Shot 2019-07-30 at 6 14 40 PM" src="https://user-images.githubusercontent.com/6945691/62176342-ed54cc80-b2f5-11e9-930f-2070026d98b3.png">

- Too soon to renew.
   - due date is farther than allowed in the renew (@saseestone is this sentence complete?)
- Renew Reserve items in person.
- Renew Media items in person.
   - can we know that the item is Reserve vs Media? Otherwise, "Renew Reserve or Media items in person" with the caveat that the message might need to be changed if policy changes.
- No. Another user is waiting for this item.
   - it has been recalled or there is a hold on it
- No online renewals left; you may renew this item in person.
   - 0 unseen renewals
- No renewals left for this item.
   - BorrowDirect items at least
- Item is assumed lost; you must pay the fee or return the item.
- No. Claim review is in process.
- No. Your status is blocked. (or barred)

**Comment by saseestone** [comment]
For "Too soon to renew" - the due date is farther than allowed in the circulation policy for unseen renewals.

**Comment by cbeer** [comment]
This is very similar to #291

**Comment by jgreben** [comment]
@jvine is there an order of preference to display these reasons for non-renewal if more than one of them should apply?

**Comment by saseestone** [comment]
Sarah's order.  Should be confirmed by @jvine:

1. No. Your status is blocked. (or barred)
2. Item is assumed lost; you must pay the fee or return the item.
3. No. Another user is waiting for this item.
- it has been recalled or there is a hold on it
4. No. Claim review is in process.
5. No online renewals left; you may renew this item in person.
- 0 unseen renewals
6. No renewals left for this item.
- 0 renewals left (BorrowDirect items will never allow renewals)
7. Renew Reserve items in person.
8. Renew Media items in person.
- can we know that the item is Reserve vs Media? Otherwise, "Renew Reserve or Media items in person" with the caveat that the message might need to be changed if policy changes.
--Sarah says: We use different CircRules for Reserve and Media.  Don't know if that would help, but happy to map it if it does.
--Sarah says: also note that Faculty members CAN renew Media items online (unseen) 1 time.  
9. Too soon to renew.
- due date is farther than allowed in the circulation policy for unseen renewals

**Comment by jvine** [comment]
Agree with Sarah’s order.

**Comment by jgreben** [comment]
Fixed by #400
