### ISSUE TITLE
Renew one checkout

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#48]
Prerequisite: #18

Allow the user to renew eligible materials.

Q: What's eligible to be renewed? Does the symphony API give us that information?

Here's a small button for renewing the item:
<img width="370" alt="Screen Shot 2019-07-10 at 07 50 03" src="https://user-images.githubusercontent.com/111218/60979388-7eccb200-a2e7-11e9-9f14-2cb4ce6e2ccb.png">

Q: @jvine: are there any additional renew controls in the expanded version of an item? Tooltips/labels for the renew button?

And a flash message:
<img width="386" alt="Screen Shot 2019-07-10 at 07 50 14" src="https://user-images.githubusercontent.com/111218/60979404-84c29300-a2e7-11e9-9768-c123b0e182d2.png">

**Comment by jvine** [comment]
Revised design around single-item renewals. 

The most common action is to renew all eligible items. The list needs some indicator of which items are eligible/will be included in this action. The intent of the item-level icon was originally just to indicate renewable status, with a visual connection to the icon on the button. Then it seemed possible to use the same icon as an affordance for the action itself. But this turns out to introduce complexities and inconsistencies we don't want. An eventual goal is to make the entire closed transaction clickable to open its details, so exposing item-level actions in the closed state would complicate that as well.

So we're reverting to using the icon in the status row as an indicator only. It's not blue, and it's closely associated with the due date, it has an aria-label of "renewable". 
<img width="421" alt="single renewal closed" src="https://user-images.githubusercontent.com/6945691/61159641-85a72080-a4b1-11e9-9ef4-6837376b22b7.png">

When the transaction is open, the first option is either:
- a message indicating why the item can't be renewed
- a "Renew this item" action (button styled as icon+link)

<img width="417" alt="single renewal open" src="https://user-images.githubusercontent.com/6945691/61159649-89d33e00-a4b1-11e9-9c36-7d911814b4b4.png">

What happens when the user clicks this button is still a question. Ideally, it would feel like a small action:  the due date would be updated (with aria-live update), the "last renewed" date will be added or updated, the "renewable" icon would be removed, focus would remain on the selected item.

However... the location of the item in the sort order (if sorted by due date, the default) will change. Will this require a page refresh? Can we dynamically move the item in the list without disorienting the user? Do we leave it out of sequence until the user re-sorts or refreshes the page? **What is technically possible here?**

(And yes, we have some usability concerns around using the icon as status in one location and action in another. Will need to test.)

**Comment by shelleydoljack** [comment]
@saseestone see Chris' question above ("What's eligible to be renewed?). Symphony WS gives us the following fields from the charge record: 
```
{"name": "patron", "type": "resource", "required": true, "nullable": false,…},
{"name": "item", "type": "resource", "required": true, "nullable": false,…},
{"name": "checkOutDate", "type": "datetime", "required": false, "nullable": true,…},
{"name": "circulationRule", "type": "resource", "required": false, "nullable": false,…},
{"name": "claimsReturnedDate", "type": "date", "required": false, "nullable": true,…},
{"name": "dueDate", "type": "datetime", "required": false, "nullable": true,…},
{"name": "library", "type": "resource", "required": false, "nullable": false,…},
{"name": "overdue", "type": "boolean", "required": false, "nullable": true,…},
{"name": "estimatedOverdueAmount", "type": "money", "required": false, "nullable": true,…},
{"name": "piecesReturned", "type": "numeric", "required": false, "nullable": false,…},
{"name": "recallDueDate", "type": "datetime", "required": false, "nullable": true,…},
{"name": "recalledDate", "type": "date", "required": false, "nullable": true,…},
{"name": "renewalCount", "type": "numeric", "required": false, "nullable": true,…},
{"name": "renewalDate", "type": "datetime", "required": false, "nullable": true,…},
{"name": "status", "type": "set", "required": false, "nullable": true,…},
{"name": "seenRenewalsRemaining", "type": "numeric", "required": false, "nullable": true,…},
{"name": "unseenRenewalsRemaining", "type": "numeric", "required": false, "nullable": true,…}
```
And we can lookup the circulation rule to get the renewFromPeriod if we need to use that value to determine if an item can be renewed (example response for circ rule 28DNF):
```
{
"resource": "/policy/circulationRule",
"key": "28DNF2",
"fields":{
"policyNumber": 5,
"description": "",
"displayName": "28DNF2",
"loanPeriod":{"resource": "/policy/loanPeriod", "key": "28D"},
"billStructure":{"resource": "/policy/billStructure", "key": "RECODONLY"},
"renewLimit": 25000,
"chargeable": true,
"gracePeriod": 0,
"recallGracePeriod": 7,
"graceType":{"resource": "/policy/graceType", "key": "DAYS"},
"overridable": false,
"recallLoanPeriod":{"resource": "/policy/loanPeriod", "key": "NONE"},
"alternateLoanPeriod":{"resource": "/policy/loanPeriod", "key": "8D"},
"maxCharges": 25000,
"keepHistory": false,
"unseenRenewLimit": 2,
"renewFromDueDate": true,
"renewFromPeriod": 14
}
```

**Comment by mejackreed** [comment]
@jvine  Refreshing and moving things around without a refresh is technically possible, but could be prone to some errors. I would perhaps try to approach it as a form submission that then reloaded the page if that is possible?

**Comment by jvine** [comment]
It's important to the overall UX that the single-item transactions be as lightweight as possible. 

I would like to see something like this happen in-place:
![renew1item](https://user-images.githubusercontent.com/6945691/61398471-f0c17000-a880-11e9-826d-af2b4ef156e5.gif)

...leaving the item in its current location in the list, with the new date highlighted to show a) it's new, and b) it's out of sequence. The user can choose to re-sort the list if needed. Seeing the transaction status change, and leaving the user in place to act on another item is more important than the order. 

A page refresh from this action would be disconcerting; and we'd need to consider where the user's focus would be in the re-loaded page.

**Comment by cbeer** [comment]
In terms of development, it sounds like we should start with the simple form submit -> page refresh (which we'll certainly need anyway to support non-javascript browser), and then progressively enhance with javascript.
