### ISSUE TITLE
Modifying single requests

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#51]
Prerequisite: #50 

Inside the expanded request is a form for updating a request:

<img width="374" alt="Screen Shot 2019-07-10 at 07 59 15" src="https://user-images.githubusercontent.com/111218/60980063-9f493c00-a2e8-11e9-87dd-daf2de4420c9.png">

Q: @jvine : should there be some kind of submit button?

**Comment by jvine** [comment]
I'm not able to find a good edit-in-place model for mobile, and given discussions around Renew one item, it seems like that interaction style may not be possible anyway. 

So instead... Modify an individual request uses a version of the Bulk dialog. 

Request detail now looks like all other detail panels:
<img width="363" alt="request detail" src="https://user-images.githubusercontent.com/6945691/61568605-c0243680-aa38-11e9-9293-c1de6ba4ec47.png">

Clicking on "Cancel or change this request" opens the dialog:
<img width="361" alt="change one request" src="https://user-images.githubusercontent.com/6945691/61568580-9cf98700-aa38-11e9-94a5-f280de82e954.png">

which includes a truncated portion of the specific title being acted on, and singular "this" instead of "these". Values default to what is currently selected for the item.

**Comment by jvine** [comment]
Note that as we add additional types of requests, some options will not be available. Paging requests don't allow a "not needed after" date; the user can't change the pickup library for in-library-use items like maps and special collections. May consider using a simple "Cancel this item" action (like "Renew this item") at some point.

**Comment by mejackreed** [comment]
@jvine I have a few questions about the form elements for the "change request" part.

1. How do we determine which libraries this can be picked up? Is that something that Sympohony should give us?

2. Is there a minimum / maximum date that we can change "not needed after" to be?

3. Is there a preferred accessibility approach to the date picker?

**Comment by jvine** [comment]
2) The current My Account limited me at 2038 - so 19 years in the future? @saseestone or @jgreben may know if there's a policy restriction.

3) I would prefer to use the default HTML5 date input, so that it uses the browser/OS default control, except not all browsers support it. Can we make the label "Not needed after (mm/dd/yyyy)" to provide format context,  and allow direct text input for browsers that don't support the date control? And validate on submit? Accessibility prefers direct input over a custom calendar popup.

**Comment by jgreben** [comment]
> * The current My Account limited me at 2038 - so 19 years in the future? @saseestone or @jgreben may know if there's a policy restriction.

There is nothing in the current web app that sets or limits the date to 2038. That definitely comes from a system message. I can't find where that is set in any policy, so maybe Sarah knows or we can ask Kat Stephens.
