### ISSUE TITLE
Add patron privileges information to the summary page

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#53]
SUNETID accounts:
<img width="388" alt="Screen Shot 2019-07-10 at 08 06 03" src="https://user-images.githubusercontent.com/111218/60980572-9147eb00-a2e9-11e9-9faa-051f57af974f.png">

Paid accounts:
<img width="367" alt="Screen Shot 2019-07-10 at 08 06 19" src="https://user-images.githubusercontent.com/111218/60980594-9ad15300-a2e9-11e9-8af9-d95ecc0efcae.png">

Paid accounts also have a check out quota:
<img width="351" alt="Screen Shot 2019-07-10 at 08 06 54" src="https://user-images.githubusercontent.com/111218/60980631-b177aa00-a2e9-11e9-89b9-8c0f9b9e228c.png">

Translation table for patron status:

```
    'COLLECTION' => 'Blocked',
    'BARRED' => 'Blocked',
    'BLOCKED' => 'Blocked',
    'OK' => 'OK',
    'DELINQUENT' => 'OK'
```

**Comment by jvine** [comment]
For BARRED, I'd like to try a translation of "Contact us" instead of "Blocked".

<img width="98" alt="Screen Shot 2019-07-17 at 11 44 18 AM" src="https://user-images.githubusercontent.com/6945691/61402581-46e5e180-a888-11e9-9fce-d88b54074846.png">

The user can clear the BLOCKED status by paying their fines. They can't do anything about BARRED _except_ contact Access Services. I'd like that to be visible in the nav, not just the summary page.

**Comment by cbeer** [comment]
Remaining work split to #216
