### ISSUE TITLE
Button for Scheduling Green entry

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/mylibrary#543]
Given a Patron, the Patron should:

* See a new "Building access" row in the patron information section of the Summary index view. 

If the Patron is an eligible patron (for launch: faculty, graduate students, postdocs, fellows, and visiting scholars), they should:

* See a button on the "Building access" row to schedule entry to Green Library
* Click the button and have the form autopopulate visible, editable fields with their name (`name`) and email (`email`), and hidden fields with their name (`sul_myaccount_name`), email (`sul_myaccount_email`), and SUNetID (`sul_myaccount_sunetid`)
* Submit the form to schedule a time and receive an email

If the Patron is not eligible, they should:

* See "Not eligible for access in Stage 1" on the "Building access" row (wording may change)

**Mockups/Other information**
* [Static mockups](https://docs.google.com/document/d/13enMGvD-vT73r44NOQyOgYSqustAmXzNgDpfYEmgyNU/edit)
* [JSFiddle demo](https://jsfiddle.net/anarchivist/bp6fzxnh/)
* [Dynamic mockups](https://anarchivist.github.io/myaccount-so/index.html)
* [EH&S Return to Research site](https://ehs.stanford.edu/returntoresearch)

**Oncehub Form ID**
StanfordLibrariesGreenEntry

**Comment by saseestone** [comment]
User groups and Symphony user profiles:

faculty = CNF, MXF
grad students = MXD, RED, REG, REG-SUM, REU
postdocs = (still confirming)

**Comment by saseestone** [comment]
Requirements changed on 5/28/20 to include "fellows and visiting scholars".

Visiting Scholars = MXAS
Fellows = CNAC

Fellows are problematic because they share a User Profile with Academic Staff (which have not been cleared for building access in the requirements.)  In Symphony, we do have the Registry Affiliation Type stored in the user's record.  However, I don't think we're currently using it in MyLibrary, and have no idea if we could get it passed using web services.  Shelley will know.
