### ISSUE TITLE
Add scheduler for EAL

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/mylibrary#557]
> EAL anticipates opening up for visits by appointment on Monday, Jun 22.
Hours would be 10 - 2 (vs 3 pm for Green)
Appointment windows would be 1 hour each, with 12 slots per window (max capacity of 48 people for the day)
Eligible group is the same as Green access

* [x] Create ScheduleOnce event type and booking page (`StanfordLibrariesEastAsiaLibraryEntry`)
* [x] Create shared calendar and provide access to EAL staff who need to see it 
   * [x] SNOW ticket for resource calendar (`RITM00126051`/`REQ00125237`)
   * [x] add calendar to @anarchivist outlook
   * [x] grant access to EAL staff
* [x] Limit appointments to start on 6/22
* [x] Configure My Account to show embedded booking modal

**Comment by jvine** [comment]
My inclination for My Account would be to replace the current "Schedule access to Green Library" button with a drop-down button where we have the flexibility to add more libraries, rather than creating a stack of individual buttons. 

Click button, show list of available libraries, click library name in list, open modal. 

<img width="178" alt="Screen Shot 2020-06-12 at 4 04 27 PM" src="https://user-images.githubusercontent.com/6945691/84680671-e58b2000-aee7-11ea-864a-750b31658222.png">

<img width="187" alt="Screen Shot 2020-06-12 at 4 04 18 PM" src="https://user-images.githubusercontent.com/6945691/84680672-e623b680-aee7-11ea-85c7-204ad5cd9ecb.png">
