### ISSUE TITLE
Hook up the ability to change the patron's PIN using `/patronpin`

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#739]
Requires mod-users 18.3

**Comment by thatbudakguy** [comment]
needs investigation to see if patron pin verification works on latest mod-users (now installed) — see #740

**Comment by jcoyne** [comment]
Do we have a pin to test with?

**Comment by thatbudakguy** [comment]
what I did to test this was to just change one of the courtesy patron's PINs to a known value, since we know that API works (or it reports success, anyway).

the person whose pin I changed was Michael J Abbott (id `35ce758e-a0b3-4622-b0cb-939cead3ad71`, username/barcode `2552917744`). i think I made his pin `mypin`, but if that wasn't it, you can just set it again by `POST`ing to `/patronpin`.

**Comment by jcoyne** [comment]
@cbeer can you clarify, whether this means to hook up the UI so that a patron can change their pin?

**Comment by cbeer** [comment]
We should hook this up to the UI. Symphony did some of the lifting for us (looking up a patron's email from their barcode, sending an email with a reset token, etc) and we'll need to find out if FOLIO does anything similar or if we need to implement that behavior in this app.

**Comment by thatbudakguy** [comment]
FOLIO [does not do this for us](https://wiki.folio.org/pages/viewpage.action?pageId=65111663).
> The functionality for an email based PIN reset will be addressed later and should work similar to FOLIOs password reset mechanism.

**Comment by thatbudakguy** [comment]
- [ ] generate a reset token in the `FolioClient` based on the patron's library id, with an expiration date
- [ ] send an email to the patron with a link that takes them back to the change pin form and provides the token
