### ISSUE TITLE
Change tab titles for proxy/sponsor layout when logged in as a proxy

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/mylibrary#871]
When logged in as a Proxy: the first tab is personal activity, the second tab displays the activity of all proxies with the same Sponsor, including any proxy activity by the given Proxy. 

![Screenshot 2023-07-06 at 14 36 56](https://github.com/sul-dlss/mylibrary/assets/1328900/f781b442-4e5b-45e1-9a9c-9e4d3502273f)

Tasks:
1. Remove "Proxy" from being appended to beginning of the displayed name in first tab title. Given the existing text for Sponsors (see below), I think "Self" would be a good choice here.
2. Change the "Other proxies" label to something like "Proxy group activity". 

The template to change is here https://github.com/sul-dlss/mylibrary/blob/f1d5645a26e2689aa859c0dc34416f6b5cb50138/app/views/shared/_group_tabs.html.erb#L11

For reference, here is what tab titles look like when logged in as a Sponsor.

![Screenshot 2023-07-06 at 15 40 38](https://github.com/sul-dlss/mylibrary/assets/1328900/a234268f-cff5-42f9-aed9-1e053d6ddf38)

**Comment by cbeer** [comment]
In Symphony land, proxies are dedicated users who are only proxies for the group sponsor. In FOLIO, proxies are (may be) applied to actual patron accounts, so the proxy/other proxy distinction doesn't make a lot of sense.

For FOLIO launch, instead of going through a bigger redesign, we're proposing to give proxies a "self" tab and a "proxy group" tab (combining the patron's activity in the proxy group with all the other proxy activity)... if that's acceptable, we just need a good label for that other tab.

We should also decide if it's worth trying to do those labels right now, or just make the switch as part of the Symphony/FOLIO cutover. We're likely the only people who would test this functionality, so 🤷
