### ISSUE TITLE
[mylibrary/prod] FolioClient::IlsError: Renew request for user_id: 2db55177-a597-42ca-8f1b-250a122a624d, item_id: cb01b312-9e1c-5727-bed5-95a3c37f6349 was not successful. status: 422, {
  "errors" : [ {
    "message" : "Cannot renew loan when user is inactive or expired",
    "parameters" : [ {
      "key" : "reason",
      "value" : "User is inactive."
    } ]
  } ]
}

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#937]
## Backtrace

    line 238 of [PROJECT_ROOT]/app/services/folio_client.rb: check_response
    line 107 of [PROJECT_ROOT]/app/services/folio_client.rb: renew_item_request
    line 84 of [PROJECT_ROOT]/app/services/folio_client.rb: renew_item

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/62116/faults/99801222)

**Comment by thatbudakguy** [comment]
probably we shouldn't have shown this inactive user a renew button in the first place. can we avoid doing that?

**Comment by corylown** [comment]
It looks like a patron account can be inactive and `expirationDate` can be nil at the same time. We're not accounting for this case when checking if someone can renew. It's a little unclear whether there's a meaningful difference between a patron account that is inactive because the expirationDate passed or...is just inactive with no expirationDate.
