### ISSUE TITLE
Alert PIN users that they have to reset their PIN in FOLIO

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/mylibrary#943]
can we improve on the existing messaging/UI:

![Image](https://github.com/sul-dlss/mylibrary/assets/4924494/c64cb496-7205-4987-a0c3-600f3988e617)

**Comment by marlo-longley** [comment]
Was reading Chris's comment in #946 and thought this could help -- I recall a conversation with @saseestone where we wondered about placing the messaging close to the button impacting these users (the Log in with PIN button) rather than as a global/top level alert. Not sure if that's helpful and there may be obvious UX reasons not to do this!

It would be awesome to have a design that covers both the pages screenshotted below. A process we have used in the past is to post a quick mockup of a potential design here in the ticket, get Sarah's OK and some eyes from the team here in the ticket thread, have any discussion of pros/cons here in the ticket if needed, and then remove the design-needed tag once we're all good. At that point we would consider writing code and/or reassigning the ticket to a developer.

I am totally open to other processes but I thought it could be helpful to explain a general way we've worked in the past (or at least my impression of it). If this is redundant knowledge apologies!

![Screenshot 2023-09-07 at 11 42 18](https://github.com/sul-dlss/mylibrary/assets/1328900/b6fb1abf-048e-4df1-9c08-6772d0d7d69a)
![Screenshot 2023-09-07 at 11 42 28](https://github.com/sul-dlss/mylibrary/assets/1328900/0b1e3133-c0f2-442d-81a5-b38a85e3600f)

**Comment by alundgard** [comment]
Thank you @marlo-longley ! This is very helpful feedback. I really appreciate it. Especially, thanks for explaining the team's common processes and practices. That's great for me to know, and I'm more than happy to contribute in whatever way works best for the team. :-)

And yes, I agree with your and Sarah's design intuition. After getting more context from Chris, I also thought a global alert is maybe not intervening at the right level. Makes sense to put the PIN-specific content beneath the Proxy header. I'll post some mockups today.

**Comment by alundgard** [comment]
Here are some mockups of a PIN message and placement (cc @saseestone @cbeer @marlo-longley ). Feedback welcome!
<img width="1624" alt="Screenshot 2023-09-08 at 12 44 40 PM" src="https://github.com/sul-dlss/mylibrary/assets/2343316/455f1fd8-8ce6-4057-be3b-3e797ff4669e">
<img width="1624" alt="Screenshot 2023-09-08 at 12 51 34 PM" src="https://github.com/sul-dlss/mylibrary/assets/2343316/56d4859d-47f0-492f-aa8c-9db3384ae4cb">

I'm also wondering if the "update" and "Request/Reset" language could be simplified to make the messaging clearer? Specifically, is "resetting/updating a PIN" equivalent to "requesting a new PIN"?

I can understand how the dual-messaging (Request/Reset) targets different user groups (new users versus returning users). But it's a bit confusing that the "Request a PIN" button on the main page routes to the `reset_pin` page with a "Request/Reset" header.

If it's important to maintain the Request/Reset, I will update the mockup messaging accordingly.

**Comment by marlo-longley** [comment]
Thanks @alundgard ! I agree that the request/reset language can be confusing and would be happy to follow your recommendation for the clearest language, but leave it to @saseestone to chime in on whether that would conflict with any user needs.

**Comment by thatbudakguy** [comment]
decision: let's optimistically move forward with this design, and make sure we keep the alert around for awhile longer to give people a chance to see it.

**Comment by marlo-longley** [comment]
Closed by https://github.com/sul-dlss/mylibrary/pull/960
