### ISSUE TITLE
[mylibrary/prod] SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#974]
## Backtrace

    line 159 of [PROJECT_ROOT]/app/models/folio/patron.rb: sponsor?
    line 11 of [PROJECT_ROOT]/app/models/folio/group.rb: sponsor
    line 21 of [PROJECT_ROOT]/app/models/folio/group.rb: barred?

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/62116/faults/101065564)

**Comment by marlo-longley** [comment]
This happened because two people were in a circular proxy/sponsor relationship where they were both proxy and sponsor to each other.
Sarah confirmed that this was a data error. Shelley had to go in and manually fix the relationship--  privileges staff was not able to do this in the UI.
At this time we won't make code changes, but we may want to refactor the `Group` class in the future to better reflect the FOLIO data model. In that case, we could potentially rely more heavily on the `Patron` class itself rather than a subclass, make `proxy? = true` more of a special case, and use `patron_or_group` differently or less in the templates (these were some directions we discussed when looking at this ticket).
